from .base import *


SECRET_KEY = 'i^65f-goyu3or-)ngoa)7rms^6ka474l_d%0$l$t^f(=rovxb0'
DEBUG = True
ALLOWED_HOSTS = []
BASE_URL = 'http://localhost:8000'

MAILCHIMP_SEND_EMAILS = False
MAILCHIMP_API_KEY = 'top-secret'
MAILCHIMP_SUB_LIST_NAME = 'top-secret'
MAILCHIMP_SUBSCRIPTION_FORM_URL = '#'

RECAPTCHA_PUBLIC_KEY = '6LdcbAwUAAAAANnJSDxlqwrjWDPMyAXI_nTU_xFF'
RECAPTCHA_PRIVATE_KEY = '6LdcbAwUAAAAANzXPosD_ax8pKcnVY0DFylZiG2N'
