# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 09:22
from __future__ import unicode_literals

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True)),
                ('featured_image', models.ImageField(upload_to=blog.utils.upload_directory_path)),
                ('short', models.TextField()),
            ],
        ),
    ]
