# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-11 08:40
from __future__ import unicode_literals

import blog.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161104_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.utils.upload_directory_path)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.BlogPost')),
            ],
        ),
    ]
