# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
