# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 10:24
from __future__ import unicode_literals

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161116_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preview_key',
            field=models.CharField(default=blog.utils.generate_preview_key, max_length=100),
        ),
    ]
