# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 18, 11, 20, 43, 522853, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
